spring.application.name=microservicio
server.port=8080

# AWS S3 Configuration
aws.s3.bucket-name=bucket-inscripcionesgrupo2
aws.region=us-east-1
aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}

# Spring Security OAuth2 (validación de tokens JWT desde Azure AD B2C)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/0a871409-07d4-49ac-b239-899c125b9820/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=820a8791-373a-4785-8b59-20979309bad4